[tool.ruff]
line-length = 119

[tool.ruff.lint]
preview = true
extend-select = [
    "B009", # static getattr
    "B010", # static setattr
    "CPY", # Copyright
    "E", # PEP8 errors
    "F", # PEP8 formatting
    "I", # Import sorting
    "TID251", # Banned API
    "UP", # Pyupgrade
    "W", # PEP8 warnings
]
ignore = [
    "E501", # Line length (handled by ruff-format)
    "E741", # Ambiguous variable name
    "W605", # Invalid escape sequence
    "UP007", # X | Y type annotations
    "UP035", # Import from `collections.abc` instead: `Callable`
    "SIM115", # Use a context manager for opening files
    "SIM118", # Use `key in dict` instead of `key in dict.keys()`
    "UP045", # Use `X | None` for type annotation
    "PLR0402", # Use `from torch import nn` in lieu of alias
    "B020", # Loop control variable `path` overrides iterable it iterates
    "PERF402", # Use `list` or `list.copy` to create a copy of a list
    "EXE001", # Shebang is present but file is not executable
    "E731", # Do not assign a `lambda` expression, use a `def`
    "DTZ005", # `datetime.datetime.now()` called without a `tz` argument
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"] # Ignore unused imports only on init files.

[tool.ruff.lint.isort]
lines-after-imports = 2

[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"