name: Pre-commit checks
on:
  push:
    branches: ['workflows']
  pull_request:
    branches: ['workflows']
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pip install ruff
      - name: Run pre-commit
        run: |
          pre-commit run --all-files
